DEFAULT_BENCHMARK = "^NSEI"  # Nifty 50. You may try "^CNX500" or "^CRSLDX" if supported by Yahoo Finance.

DEFAULT_LOOKBACK_PERIOD = "2y"
DEFAULT_INTERVAL = "1d"

DEFAULT_MIN_PRICE = 20.0
DEFAULT_MIN_AVG_TRADED_VALUE_CR = 2.0

DEFAULT_PRICE_VS_150DMA_MIN = 0.95
DEFAULT_PRICE_VS_150DMA_MAX = 1.15
DEFAULT_MIN_BASE_WEEKS = 4
DEFAULT_TOP_N = 50

TRADINGVIEW_URL_TEMPLATE = "https://in.tradingview.com/chart/?symbol=NSE:{symbol}"
